apiVersion: v1
kind: Secret

metadata:
  name: backend-secret
  namespace: app

type: Opaque

stringData:
  MONGODB_URI: "mongodb+srv://todo-user:bhuHLJogftbqgckf@freemongodbcluster.sglodw3.mongodb.net/todo_db"
